database:
  driver: "postgres"
  # user and password can be stored in secret manager
  user: "user"
  password: "password"
  dbname: "product-catalogue"
  host: "localhost"
  port: 5432
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 9